server:
  port: 8501

spring:
  application:
    name: customer-service
  boot:
    admin:
      client:
        url: http://localhost:8508
  data:
    mongodb:
      host: localhost
      port: 27020
      database: customer
      auto-index-creation: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/